#!/usr/bin/env python3
"""Replacement for bin2cpp.exe (Windows-only) used by the MSVC build.

Emits Embedded/<stem>.h / .cpp exposing the same bin2cpp:: API the existing
source already calls, so no call site has to change:

    bin2cpp::File const&  with .getBuffer() -> char const*
                               .getSize()   -> size_t
    bin2cpp::get<Name>File()

Getter names are an explicit table rather than derived, because bin2cpp's
mangling rules (drop '-', keep '_', capitalise the extension) are quirky and
guessing them wrong fails at link time rather than here.
"""
import sys, pathlib

# (source asset, output stem, getter name)
ASSETS = [
    ("RogueAssistant_mGBA.lua",   "RogueAssistant_mGBA",  "getRogueAssistant_mGBALuaFile"),
    ("WobbuffetImage.png",        "WobbuffetImage",       "getWobbuffetImagePngFile"),
    ("pokemon-emerald-pro.ttf",   "pokemon-emerald-pro",  "getPokemonemeraldproTtfFile"),
    ("poketch_frame.png",         "poketch_frame",        "getPoketch_framePngFile"),
]

COMMON_H = """// Generated by embed_assets.py - do not edit.
#pragma once
#include <cstddef>

namespace bin2cpp
{
    class File
    {
    public:
        virtual ~File() = default;
        virtual char const* getBuffer() const = 0;
        virtual size_t getSize() const = 0;
    };
}
"""

HEADER = """// Generated by embed_assets.py from {src} - do not edit.
#pragma once
#include "bin2cpp_common.h"

namespace bin2cpp
{{
    File const& {getter}();
}}
"""

SOURCE_HEAD = """// Generated by embed_assets.py from {src} - do not edit.
#include "{stem}.h"

namespace bin2cpp
{{
namespace {cls}_detail
{{
    // Trailing NUL so callers that treat this as a C string (e.g. the .lua
    // dump in Main.cpp) stay in bounds. It is NOT counted in getSize().
    static unsigned char const s_Data[] = {{
"""

SOURCE_TAIL = """    }};

    class {cls} : public File
    {{
    public:
        char const* getBuffer() const override {{ return reinterpret_cast<char const*>(s_Data); }}
        size_t getSize() const override {{ return {size}; }}
    }};

    static {cls} const s_Instance;
}}

    File const& {getter}() {{ return {cls}_detail::s_Instance; }}
}}
"""

def emit(asset_dir: pathlib.Path, out_dir: pathlib.Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "bin2cpp_common.h").write_text(COMMON_H)

    for src, stem, getter in ASSETS:
        raw = (asset_dir / src).read_bytes()

        (out_dir / f"{stem}.h").write_text(HEADER.format(src=src, getter=getter))

        cls = f"{stem.replace(chr(45), chr(95))}File"
        body = [SOURCE_HEAD.format(src=src, stem=stem, cls=cls)]
        for i in range(0, len(raw), 16):
            row = ", ".join(f"{b:#04x}" for b in raw[i:i + 16])
            body.append(f"        {row},\n")
        body.append("        0x00\n")  # the NUL described above
        body.append(SOURCE_TAIL.format(cls=cls, size=len(raw), getter=getter))
        (out_dir / f"{stem}.cpp").write_text("".join(body))
        print(f"  embedded {src} ({len(raw)} bytes) -> {stem}.cpp")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: embed_assets.py <assets-dir> <output-dir>")
    emit(pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]))
